### ISSUE TITLE
Failiure to limit analysis to less than 4 plates

### ISSUE THREAD

**Issue by local-minimum** [local-minimum/scanomatic#102]
This was discovered while looking into #99.

If a project originally was scanned with a four plate fixture, it would still be analysed inconsistently as a four plate project even if recompiled with a two plate fixture.

**Comment by local-minimum** [comment]
Compilation will now verify that the spawning of analysis is done with the correct number of `pinning_matrices` and output a warning if there was a mismatch.

There is also a field in the project compilation model / instruction to overwrite previous pinnings, but no UI at the moment (issue #103).

Analysis will also verify the number of plates and assume pinning from the first first plates, again related to #103.

**Comment by local-minimum** [comment]
@Endimion75 Can you verify this now produces expected results?

**Comment by Endimion75** [comment]
after pulling I re-analyzed a project with a 2 plate fixture and now we get the expected result:

...
"plate_indices": [
    0,
    1
  ],
...
