### ISSUE TITLE
Problem loading plates and growth graphs with re-analyzed projects

### ISSUE THREAD

**Issue by Erlor** [local-minimum/scanomatic#107]
1.4.140 QC display plates and graphs for projects analyzed in 1.4.85 but not for projects analyzed in 1.4.140

**Comment by local-minimum** [comment]
Could you verify that this remains in the current `v1.4.144`?

**Comment by local-minimum** [comment]
Also, there was an underlying bug in the core code so it might not be an UI issue. Awaiting conformation that it is. Consider using #74 API to gather the data needed to reproduce it if Luciano needs to try it out (though if you share it publicly, know that it will contain the phenotypes and growth curves of the project).

**Comment by Erlor** [comment]
Each re-analysis gives the same problem:

"ValueError: 'GrowthLag' has not been extracted, please re-run 'extract_phenotypes()' to include it."

**Comment by local-minimum** [comment]
This is now fixed in `v1.4.146`. For future bugs please include the full traceback when reporting and also please indicate exactly what you did that caused the problem.
