### ISSUE TITLE
White line in image?

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#113]
We noticed that we have a white line we previously haven't discovered. It's very apparent on this image because it goes through two of the positional markers.
We first thought this was an issue from the scanner, but we discovered that it was independent of scanner and even computer.

![new_fixture_mu3_0000_32 8345_smaller](https://cloud.githubusercontent.com/assets/8545240/24038193/a4e86140-0b00-11e7-9ac4-944174accc95.png)

**Comment by local-minimum** [comment]
This is probably one or more of the following:

1) Dirt / dust in the scanner in that "column" in the area where the scanner makes its calibrations.
2) The cutout in the fixture for the area scanner calibration may end there causing lower transparency which leads to brighter pixels in the image for that column
3) If this is not part of the cutout area for the scanner calibration but part of one of the distance pegs of the fixture, that peg may be dirty.
4) The sensor may be deteriorating / broken and in this case the scanner may need maintenance or replacement.

Issue will be closed. This will be incorporated into the wiki.

**Comment by local-minimum** [comment]
Here: https://github.com/local-minimum/scanomatic/wiki/Scanning:-Troubleshooting

**Comment by StenbergSimon** [comment]
Well it happens in the exact same location in _different scanners_ on _different computers_ so it cant't be any of those causes?

**Comment by local-minimum** [comment]
3) is possible if it is the peg edge, this will have different transparency due to vertical cut in acrylic glass.
