### ISSUE TITLE
API: compress colony response has typo on returned parameters

### ISSUE THREAD

**Issue by Endimion75** [local-minimum/scanomatic#117]
When using the  API path:

/api/data/ccc<ccc_identifier>/image/<image_identifier>/plate/<plate_number>/compress/colony/<x>/<y>

the expected response has a breaking typo:

"sucecss" instead of success

**Comment by Endimion75** [comment]
The typo seems to be related when the compression is successful only

**Comment by skymandr** [comment]
Resolved by https://github.com/local-minimum/scanomatic/commit/47de2facdb118378f03d0459deafb7d98b8657b6
