### ISSUE TITLE
Sendmail bug

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#46]
I do not receive any emails from scan-o-matic.

The error message mentions "unknown host"

**Comment by local-minimum** [comment]
Please verify if the following works:

    from scanomatic.io.mail import mail
    mail(None, "your.name@your.mail", "Test", "Test mail")

If that delivers a message check if you have local mail configs:

    from scanomatic.io.app_config import Config
    print dict(**Config().mail)

But don't paste it here in case you have passwords and such included... If it looks like the following, then everything should be good to go.

```
{'password': None,
 'port': 0,
 'server': None,
 'user': None,
 'warn_scanning_done_minutes_before': 20.0}
```
 
Else your app-configs in ```~/.scan-o-matic/``` need a fix.

**Comment by local-minimum** [comment]
Problem was relating to the scanner computer being behind router, isssue solved in experimental branch.
