### ISSUE TITLE
Project settings vs Project Compilation

### ISSUE THREAD

**Issue by local-minimum** [local-minimum/scanomatic#57]
There's a mismatch were the information is gathered when original scanning is performed.

Original compilation information ends up in project.settings, which probably isn't the best of names while any later compilation of a project (what we are really talking about) create a project.compilation. 

It is quite possible that project.settings was added to keep the original information about the images in the project as they were gathered and originally analyzed. In contrast, project.compilation gets/can get overwritten each time a new compilation is made.

It is also possible the intent is different.

Current behavior isn't critical as the following steps uses the project.settings information if the project.compilation file is missing. It seems.

- [x] Verify that project.compilation has priority over project.settings.
- [x] Verify that project.settings is used as intended
- [x] Rename project.settings to reflect that is actually the original project.compilation file.
- [ ] Ensure that a project.compilation file is created when scanning is run

**Comment by StenbergSimon** [comment]
Tested and confirmed working in dev branch
