### ISSUE TITLE
No grid image produced during scanning analysis

### ISSUE THREAD

**Issue by local-minimum** [local-minimum/scanomatic#77]
The automatic analysis following scanning doesn't produce grid images.

Attempt causes traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scanomatic/util/analysis.py", line 21, in produce_grid_images
    raise ValueError("There are no compilations in the parent directory")
ValueError: There are no compilations in the parent directory
```

**Comment by local-minimum** [comment]
The issue was caused by first compilation during scanning not using "normal" compilation file endings. This is now fixed so it will fall back to searching for those. 

In order it tries to localize:

1. `.project.compilation`
2. `.project.compilation.original`
3. `.project.settings`

However griddding currently has no way of knowing which to use if there are several files in the same class but just uses the first one found. This causes a problem for when a fixture is remade an there are several `.project.compilation`-files. Will create new issue on that topic.

**Comment by StenbergSimon** [comment]
Tested and confirmed working in dev branch
