### ISSUE TITLE
Improvements to QC

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#83]
I've started using the new QC and noticed some things that would make life much easier:

- Show the Qidx # in the curve or somewhere close to the curve? Its' nice to know where in the quality space you are
- A button or automatic view of cut out colony image from first and last scan image used in the analysis to aid evaluation of no growth/ dead cells vs empty position 
- Button to mark colony as bad in _all_ phenotypes. I think this is the most crucial part, which complicates QC significantly without it. I've noticed that the Qidx does not always capture bad noisy curves in the generation time phenotype. If curves are (correctly) marked as bad in other phenotypes, most of the cases it's a noisy curve that should not have a generation time extracted to it. The alternative now is to either write down the colony, switch phenotype and then mark it there as well. The second alternative is to disregard Qidx and just look through all 1536 curves (but that is not a preferable option). Phenotypes that capture noisy curves and marked correctly in that phenotype as bad is not present in the relative phenotypes file so the information of badness is lost between the files.
- The previous point also points to the question about normalization. Does the normalization only remove colonies from the controls phenotype-wise of the control surface?  That is to say that if a control curve is marked as bad in "std error around GT" but not in GT, is that control used in normalization? 
- It would also be nice to write out meta data in the plot as well. 
- Personally I would prefer if the directionality of the Qidix would be reversed. Now it feels reversed compared to old scan-o-matic.

**Comment by StenbergSimon** [comment]
I later have noticed that "no growth" marks all phenotypes as no growth, which serves the purpose I suggested above for now, but at the expense of not being able to distinguish no growth from a bad curve.

**Comment by local-minimum** [comment]
* No growth and empty marks all phenotypes as they refer to the entire curve while bad only marks for current phenotype. This also has implications for normalization, yes.

* We have the colony images on ToDo-list.

* **Luciano** should be able to add the quality index to the plot area somewhere quite easily.

* **Martin** can make a test inverted Quality index order and you'll say if it seems better. To be clear, at present, there's only one Quality index storting for all phenotypes. 

* Showing meta-data with the plot is on ToDo-list.

**Comment by local-minimum** [comment]
> Martin can make a test inverted Quality index order and you'll say if it seems better. To be clear, at present, there's only one Quality index storting for all phenotypes.

This is live on `Experimental` as of version 1.4.97.

**Comment by local-minimum** [comment]
Changes are now also on `Dev`.

Remaining issues:

- [ ] __Luciano__: Change the behaviour of the `BadData` marking so that it markes all phenotypes by default.
- [ ] __Luciano__: Add the quality index of the curve being shown near the graph (because it is a future feature to also have strain information showing, it is probably good to start a title or legend field).
- [ ] __Lucinao__: Optional, add another `BadData` marking with a `1` on the icon and key-bind it to the key below the current key for `BadData` and let this version only mark the current phenotype.

_As a clarification, let `OK` remain to only set `OK` for current or add another `OK` with a `1` on it like with the `BadData`_

**Comment by StenbergSimon** [comment]
Still the quality index is experienced to be the same as before. Not sure what the mechanisms are since the actual quality index is hidden. 
It would be preferable to start at the worst curve and work ones way to the best curve when deleting or ok'ing curves.

**Comment by local-minimum** [comment]
As of `v1.4.146` the QC index should now be reversed. I will close this multi-issue now. Please open individual specific issues for remaining improvements.

**Comment by local-minimum** [comment]
Superseeded of #108 , #109 and #110.
