### ISSUE TITLE
manual regridding expects fixture.config to be in ./analysis

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#90]
During manual regridding using the GUI, SoM will tell you that the fixture file was not found. SoM most likely looks for the fixture file in the analysis subdirectory since moving the file there allows SoM to find it. However, the default behaviour during scanning is that the fixture.config file is placed in the project directory. That is more sensible since the analysis subdirectory does not exists until analysis. 

Only tested in dev branch.

**Comment by local-minimum** [comment]
This doesn't seem to be the case in experimental. Can you verify this is still an issue.

**Comment by local-minimum** [comment]
To be specific, it assumes that the local fixture is in the same directory as the project compilation.

**Comment by local-minimum** [comment]
Will close this next week if not verified still an issue
