### ISSUE TITLE
compilation manual selection of images

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#91]
When deselecting images for compilation, it seems to run the compilation with all images in the directory anyway.

**Comment by local-minimum** [comment]
This should work as of `v1.4.126` in `experimental`.

**Comment by local-minimum** [comment]
I've tested and it works here now.

**Comment by StenbergSimon** [comment]
Tried on latest experimental branch. Still includes all images regardless if some are deselected. 
I started with all selected, and then deselected ~20 last images. Still get 217 images in the .project.compilation file.

**Comment by local-minimum** [comment]
It seems there is a difference between deselecting all and then activating a few compared to manually deselecting a few from all selected.

In the meantime, please consider the possibility of specifying per plate inclusion of the analysis from an `rpc_client` as discussed in #64

**Comment by local-minimum** [comment]
@StenbergSimon can you include the instructions-file, I don't see any failing on the client side here and could create works with less than all images selected. If also you could also update to latest `experimental` and go to `http://localhost:5000/compile` and while selecting images for your project test if `GetIncludedImageList()` produces a matching listing if run in the browser's javascript console.

**Comment by local-minimum** [comment]
@StenbergSimon how was it, was this resolved now?

**Comment by local-minimum** [comment]
Will close this next week if not verified still an issue
