### ISSUE TITLE
project.compilation.original

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#94]
This  issue relates to #57 .

The renaming of the compilation file to project.compilation.original resulted in that SoM won't recognize this file as a (valid) compilation file in the auto-completion in the GUI.

**Comment by local-minimum** [comment]
This issue is resolved as of  `v1.4.108`.

**Comment by local-minimum** [comment]
This is now closed though not verified. Hopefully it works, if not, lets open a new issue.
