### ISSUE TITLE
Keep plate when switching phenotype

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#96]
Currently, if one changes phenotype, the selection in the GUI goes back to plate 1. It would be better if the selection stayed on whatever plate selected.

**Comment by local-minimum** [comment]
Added to this, if a curve is selected but phenotype is changed, the marking on the plate for the position displayed should stay.

**Comment by Endimion75** [comment]
Features will be added to experimental branch on next commint
