### ISSUE TITLE
Show normalized phenotypes button 

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#97]
The show normalized phenotypes button does not seem to work, at all.

**Comment by Endimion75** [comment]
I can reproduce this report.  Installed experimental branch under windows and tested it under chrome and explorer.  In both instances it worked as expected.

**Comment by Endimion75** [comment]
Can you reconfirm you have this issue?

**Comment by StenbergSimon** [comment]
It seems to be working now in 1.4.122!
