### ISSUE TITLE
No check that extracted phenotypes has data

### ISSUE THREAD

**Issue by StenbergSimon** [local-minimum/scanomatic#98]
There seem to be no checking by scanomatic that the extracted phenotypes data has actual data even if the data objects them self exists. 

Here 'InitialLag' lacks data. It's solved by removing the phenotype from the list of phenotypes to be normalized
That will result in the following error trying to normalize data:

> In [28]: P.normalize_phenotypes()
> 2017-01-13 11:38:14 -- WARNING	**Phenotyper** The phenotype 'InitialAccelerationAsymptoteAngle' has not been fully tested and verified!
> 2017-01-13 11:38:14 -- WARNING	**Phenotyper** The phenotype 'MajorImpulseAveragePopulationDoublingTime' has not been fully tested and verified!
> 2017-01-13 11:38:14 -- WARNING	**Phenotyper** The phenotype 'ExperimentLowPoint' has not been fully tested and verified!
> 2017-01-13 11:38:14 -- WARNING	**Phenotyper** The phenotype 'InitialLag' has not been fully tested and verified!
> QH6214 qhull input error: not enough points(2) to construct initial simplex (need 4)
> 
>  While executing:  | qhull d Qbb Qz Qc Qt
>  Options selected for Qhull 2012.1 2012/02/18:
>   run-id 1525502907  delaunay  Qbbound-last  Qz-infinity-point  Qcoplanar-keep
>   Qtriangulate  _pre-merge  _zero-centrum  Qinterior-keep
> ---------------------------------------------------------------------------
> QhullError                                Traceback (most recent call last)
> <ipython-input-28-bb0a4f78ece6> in <module>()
> ----> 1 P.normalize_phenotypes()
> 
> /home/scanner1/.local/lib/python2.7/site-packages/scanomatic/data_processing/phenotyper.pyc in normalize_phenotypes(self)
>    1426             data = [None if plate is None else plate.filled() for plate in data]
>    1427 
> -> 1428             for id_plate, plate in enumerate(get_normalized_data(data, self._reference_surface_positions)):
>    1429                 self._normalized_phenotypes[id_plate][phenotype] = plate
>    1430 
> 
> /home/scanner1/.local/lib/python2.7/site-packages/scanomatic/data_processing/norm.pyc in get_normalized_data(data, offsets)
>     695     pre_surface = get_downsampled_plates(surface, offsets)
>     696     apply_outlier_filter(pre_surface, measure=None)
> --> 697     surface = get_normalisation_surface(surface, offsets=offsets)
>     698 
>     699     return normalisation(data, surface, log=True)
> 
> /home/scanner1/.local/lib/python2.7/site-packages/scanomatic/data_processing/norm.pyc in get_normalisation_surface(control_positions_filtered_data, control_position_coordinates, norm_sequence, use_accumulated, fill_value, offsets, apply_median_smoothing_kernel, apply_gaussian_smoothing_sigma)
>     419 
>     420                     splined_plate = griddata(anchor_points, anchor_values, (grid_x, grid_y), method=method,
> --> 421                                              fill_value=fill_value)
>     422                     missing_data = np.where(missing_data_test(plate))
>     423                     plate[missing_data] = splined_plate[missing_data]
> 
> /usr/lib/python2.7/dist-packages/scipy/interpolate/ndgriddata.pyc in griddata(points, values, xi, method, fill_value)
>     190         return ip(xi)
>     191     elif method == 'cubic' and ndim == 2:
> --> 192         ip = CloughTocher2DInterpolator(points, values, fill_value=fill_value)
>     193         return ip(xi)
>     194     else:
> 
> /usr/lib/python2.7/dist-packages/scipy/interpolate/interpnd.so in scipy.interpolate.interpnd.CloughTocher2DInterpolator.__init__ (scipy/interpolate/interpnd.c:8909)()
> 
> /usr/lib/python2.7/dist-packages/scipy/spatial/qhull.so in scipy.spatial.qhull.Delaunay.__init__ (scipy/spatial/qhull.c:14167)()
> 
> /usr/lib/python2.7/dist-packages/scipy/spatial/qhull.so in scipy.spatial.qhull._Qhull.__init__ (scipy/spatial/qhull.c:3658)()
> 
> QhullError: Qhull error

**Comment by local-minimum** [comment]
This should be fixed on `v1.4.113` on `experimental`. Please verify.

**Comment by local-minimum** [comment]
This is now closed though not verified. Hopefully it works, if not, lets open a new issue.
